name: Run Auto Submission

on:
  schedule:
    - cron: "0 */5 * * *" # يعمل كل 5 ساعات
  workflow_dispatch: # يتيح لك تشغيله يدوياً من واجهة جيت هاب

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: pip install requests

      - name: Run script
        run: python test_script.py
